---
name: geodash-plugin-angular-pipes
pipes:
  - GeoDashPipeAppend.ts
  - GeoDashPipeDefaultIfUndefinedOrBlank.ts
  - GeoDashPipeExtract.ts
  - GeoDashPipeMarkdownToHTML.ts
  - GeoDashPipePrepend.ts
  - GeoDashPipeSlugify.ts
  - GeoDashPipeTernaryDefined.ts
